export const phoneNumberRegex = /^\+?[1-9]\d{1,14}$/;
export const MIN_TAG_NAME_LENGTH = 3;

export const MAX_FILE_SIZE = 20 * 1024 * 1024; // 20mb

// ENVIRONMENT VARIABLES KEYS
export const WILSON_BE_PORT = 'WILSON_BE_PORT';
export const WILSON_BE_LOGGING = 'WILSON_BE_LOGGING';

export const WILSON_DB_HOST = 'WILSON_DB_HOST';
export const WILSON_DB_PORT = 'WILSON_DB_PORT';
export const WILSON_DB_USERNAME = 'WILSON_DB_USERNAME';
export const WILSON_DB_PASSWORD = 'WILSON_DB_PASSWORD';
export const WILSON_DB_DBNAME = 'WILSON_DB_DBNAME';

export const WILSON_AWS_ACCESS_KEY_ID = 'WILSON_AWS_ACCESS_KEY_ID';
export const WILSON_AWS_SECRET_ACCESS_KEY = 'WILSON_AWS_SECRET_ACCESS_KEY';
export const WILSON_AWS_REGION = 'WILSON_AWS_REGION';
export const WILSON_AWS_S3_BUCKET = 'WILSON_AWS_S3_BUCKET';
export const WILSON_AWS_MODEL_ARN = 'WILSON_AWS_MODEL_ARN';

export const TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID';
export const TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN';
export const TWILIO_VERIFICATION_SERVICE_SID = 'TWILIO_VERIFICATION_SERVICE_SID';

export const WILSON_JWT_SECRET = 'WILSON_JWT_SECRET';
export const WILSON_NAME_SECRET = 'WILSON_NAME_SECRET';

export const WILSON_SENTRY_DSN = 'WILSON_SENTRY_DSN';
export const WILSON_SENTRY_ENVIRONMENT = 'WILSON_SENTRY_ENVIRONMENT';

export const WILSON_SENDGRID_API_KEY = 'WILSON_SENDGRID_API_KEY';
export const WILSON_SENDGRID_FROM_EMAIL = 'WILSON_SENDGRID_FROM_EMAIL';

export const WILSON_TEST_PHONE_NUMBER = 'WILSON_TEST_PHONE_NUMBER';
export const WILSON_TEST_TWILIO_CODE = 'WILSON_TEST_TWILIO_CODE';
