export const phoneNumberRegex = /^\+?[1-9]\d{1,14}$/;

// ENVIRONMENT VARIABLES KEYS
export const WILSON_BE_PORT = 'WILSON_BE_PORT';
export const WILSON_BE_LOGGING = 'WILSON_BE_LOGGING';

export const WILSON_DB_HOST = 'WILSON_DB_HOST';
export const WILSON_DB_PORT = 'WILSON_DB_PORT';
export const WILSON_DB_USERNAME = 'WILSON_DB_USERNAME';
export const WILSON_DB_PASSWORD = 'WILSON_DB_PASSWORD';
export const WILSON_DB_DBNAME = 'WILSON_DB_DBNAME';

export const WILSON_AWS_ACCESS_KEY_ID = 'WILSON_AWS_ACCESS_KEY_ID';
export const WILSON_AWS_SECRET_ACCESS_KEY = 'WILSON_AWS_SECRET_ACCESS_KEY';
export const WILSON_AWS_REGION = 'WILSON_AWS_REGION';
export const WILSON_AWS_S3_BUCKET = 'WILSON_AWS_S3_BUCKET';
export const WILSON_AWS_MODEL_ARN = 'WILSON_AWS_MODEL_ARN';

export const TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID';
export const TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN';
export const TWILIO_VERIFICATION_SERVICE_SID = 'TWILIO_VERIFICATION_SERVICE_SID';

export const JWT_SECRET = 'JWT_SECRET';
