name: Deploy master over SSH

on: 
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: 'cd /var/www/app && git pull && npm install && chown -R www-data:www-data /var/www/app && pkill npm && pkill node && sleep 3 && npm run start:prod &'
          host: ${{ secrets.PROD_BE_HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
        env:
          CI: true

  
